version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: openalcoholics/regular_dicers_bot
    volumes:
      "./data/users.json:/usr/src/app/users.json"
      "./data/credentials.json:/usr/src/app/credentials.json"
      "./data/secrets.json:/usr/src/app/credentials.json"
