version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - "./credentials.json:/usr/src/app/credentials.json"
      - "./secrets.json:/usr/src/app/credentials.json"
      - "./state.json:/usr/src/app/state.json"

