version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

    # build the application image
    - run: docker build -t openalcoholics/regular_dicers_bot:latest-$CIRCLE_BRANCH .

    # deploy the image
    - run: docker push openalcoholics/regular_dicers_bot:latest-$CIRCLE_BRANCH

  deploy:
    docker:
      image: byrnedo/alpine-curl:latest
    # Update server image
    steps:
    - run: curl -L "http://ec2-52-59-248-193.eu-central-1.compute.amazonaws.com:8080?key=$UPDATE_KEY"
    only:
    - develop
    - master

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build
    - deploy:
        requires:
        - build
