version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

    # build the application image
    - run: docker build -t openalcoholics/regular_dicers_bot .

    # deploy the image
    - run: docker push openalcoholics/regular_dicers_bot

    # Update server image
    - run: curl -L "http://ec2-52-59-248-193.eu-central-1.compute.amazonaws.com:8080?key=$UPDATE_KEY"
