version: 2
jobs:
  run:
    docker:
      - image:
  build:
    docker:
      - image: docker:18.09-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run: sed -i -e "s/{{VERSION}}/$CIRCLE_SHA1/" main.py

      # build the application image
      - run: docker build -t openalcoholics/regular_dicers_bot:latest-$CIRCLE_BRANCH .

      # deploy the image
      - run: docker push openalcoholics/regular_dicers_bot:latest-$CIRCLE_BRANCH

  deploy:
    docker:
      - image: byrnedo/alpine-curl:latest
    # Update server image
    steps:
      - run: curl -L "http://ec2-52-59-248-193.eu-central-1.compute.amazonaws.com:8080?key=$UPDATE_KEY"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
                - master
      - deploy:
          requires:
            - build
