version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

     # build the application image
     - run: docker build -t chabare/regular_dicers_bot:$CIRCLE_BRANCH .

     # deploy the image
     - run: docker push chabare/regular_dicers_bot:$CIRCLE_BRANCH

